services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    volumes:
      - ./backend:/var/www/backend
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: easyrev
      DB_USERNAME: sail
      DB_PASSWORD: password
    networks:
      - easyrev-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'easyrev'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - sail-mysql:/var/lib/mysql
    networks:
      - easyrev-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]

networks:
  easyrev-net:
    driver: bridge

volumes:
  sail-mysql:
    driver: local